#!/bin/bash
for ip in `seq 1 254`
do
  #address=192.168.1.$ip
  address=192.168.50.$ip
  if ping -c 1 $address > /dev/null
  then
    echo "$address is online"
  else
    echo "$address is not online"
  fi
done

